name: "CI"

on:
  pull_request:
    paths-ignore:
      - "LICENSE"
      - "**.md"
  push:
    branches:
      - "main"
      - "develop"
    paths-ignore:
      - "LICENSE"
      - "**.md"

defaults:
  run:
    shell: "bash"

jobs:
  static-check:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Static Check
        run: |
          npm run check
          npm run test
